
exclude_patterns = ["**/mocks_test.go"]

name = "docker"
[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "go"

  import_root = "github.com/gogs/gogs"
[[transformers]]

enabled = true