
exclude_patterns = ["**/mocks_test.go"]

name = "docker"
[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/gogs/gogs"
[[transformers]]
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
